export enum USER_ROLE {
    STUDENT = "STUDENT",
    PARENT = "PARENT",
    OPS = "OPS",
    COUNSELOR = "COUNSELOR",
    EDUPLAN_COACH = "EDUPLAN_COACH",
    IVY_EXPERT = "IVY_EXPERT",
    ADMIN = "ADMIN",
    ALUMNI = "ALUMNI",
    SUPER_ADMIN = "SUPER_ADMIN",
    SERVICE_PROVIDER = "SERVICE_PROVIDER",
    REFERRER = "REFERRER",
    ADVISOR = "ADVISOR",
    B2B_SALES = "B2B_SALES",
    B2B_OPS = "B2B_OPS",
  }
  

