// Hardcoded document structure for "Your Documents" section
export interface YourDocumentField {
  documentKey: string;
  documentName: string;
  category: 'PRIMARY' | 'SECONDARY';
  required: boolean;
  allowMultiple: boolean;
  helpText?: string;
  order: number;
}

export const YOUR_DOCUMENTS_CONFIG: YourDocumentField[] = [
  // PRIMARY DOCUMENTS
  {
    documentKey: 'passport_first_page',
    documentName: 'Passport First Page',
    category: 'PRIMARY',
    required: true,
    allowMultiple: false,
    helpText: 'Upload first page of your passport',
    order: 1,
  },
  {
    documentKey: 'passport_last_page',
    documentName: 'Passport Last Page',
    category: 'PRIMARY',
    required: true,
    allowMultiple: false,
    helpText: 'Upload last page of your passport',
    order: 2,
  },
  {
    documentKey: 'ssc_marksheet',
    documentName: 'SSC Marksheet',
    category: 'PRIMARY',
    required: true,
    allowMultiple: false,
    helpText: 'Upload your SSC/10th grade marksheet',
    order: 3,
  },
  {
    documentKey: 'hsc_diploma_marksheet',
    documentName: 'HSC Marksheet/Diploma Marksheets',
    category: 'PRIMARY',
    required: true,
    allowMultiple: true,
    helpText: 'Upload your HSC/12th grade or Diploma marksheets (can upload multiple)',
    order: 4,
  },
  {
    documentKey: 'degree_marksheets',
    documentName: 'Degree Marksheets (All Semesters)',
    category: 'PRIMARY',
    required: true,
    allowMultiple: true,
    helpText: 'Upload all semester degree marksheets',
    order: 5,
  },
  {
    documentKey: 'aadhar_card',
    documentName: 'Aadhar Card (Both Sides)',
    category: 'PRIMARY',
    required: true,
    allowMultiple: false,
    helpText: 'Upload both sides of your Aadhar card',
    order: 6,
  },
  {
    documentKey: 'passport_photograph',
    documentName: 'Passport Size Photograph',
    category: 'PRIMARY',
    required: true,
    allowMultiple: false,
    helpText: 'Upload a recent passport size photograph',
    order: 7,
  },
  
  // SECONDARY DOCUMENTS
  {
    documentKey: 'grade_explanation',
    documentName: 'Grade Explanation Details',
    category: 'SECONDARY',
    required: false,
    allowMultiple: false,
    helpText: 'Upload grade explanation document if required',
    order: 8,
  },
  {
    documentKey: 'transcripts',
    documentName: 'Transcripts of the Highest Qualification',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload transcripts (can upload multiple)',
    order: 9,
  },
  {
    documentKey: 'sop',
    documentName: 'SOP (As per number of different courses applied)',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload Statement of Purpose for each course',
    order: 10,
  },
  {
    documentKey: 'academic_lor',
    documentName: '2/3 Academic LORs',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload 2-3 academic letters of recommendation',
    order: 11,
  },
  {
    documentKey: 'professional_lor',
    documentName: '1 Professional LOR (If worked)',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload professional letter of recommendation if you have work experience',
    order: 12,
  },
  {
    documentKey: 'references',
    documentName: '2-3 References (Name, Contact, Email, Designation, Address)',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload reference details documents',
    order: 13,
  },
  {
    documentKey: 'language_score',
    documentName: 'IELTS/PTE/Language Score Sheet',
    category: 'SECONDARY',
    required: false,
    allowMultiple: false,
    helpText: 'Upload your language proficiency test score',
    order: 14,
  },
  {
    documentKey: 'entrance_score',
    documentName: 'GRE/GMAT/SAT Score Sheet',
    category: 'SECONDARY',
    required: false,
    allowMultiple: false,
    helpText: 'Upload your entrance exam scores if applicable',
    order: 15,
  },
  {
    documentKey: 'resume_cv',
    documentName: 'Resume/CV/Profile/Portfolio',
    category: 'SECONDARY',
    required: false,
    allowMultiple: false,
    helpText: 'Upload your resume or CV',
    order: 16,
  },
  {
    documentKey: 'work_experience',
    documentName: 'Work Experience Letter/Internship Letter',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload work experience or internship letters',
    order: 17,
  },
  {
    documentKey: 'immigration_history',
    documentName: 'Immigration History (If Any)',
    category: 'SECONDARY',
    required: false,
    allowMultiple: false,
    helpText: 'Upload immigration history documents if applicable',
    order: 18,
  },
  {
    documentKey: 'academic_programs',
    documentName: 'Certificates of Other Academic Programs Attended',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload certificates of additional academic programs',
    order: 19,
  },
  {
    documentKey: 'workshop_certificates',
    documentName: 'Certificate of any Workshop/Seminar Attended',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload workshop or seminar certificates',
    order: 20,
  },
  {
    documentKey: 'social_contribution',
    documentName: 'Certificate of any Social Contribution Made',
    category: 'SECONDARY',
    required: false,
    allowMultiple: true,
    helpText: 'Upload certificates of social contributions or volunteer work',
    order: 21,
  },
];

